#!/bin/sh

PROJECT_ROOT=$(git rev-parse --show-toplevel)
TEST_RESULTS_PATH="${PROJECT_ROOT}/reports/TestResults_$(date +%Y%m%d%H%M%S).xcresult"

xcodebuild clean test -scheme AmpUp -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' -project "${PROJECT_ROOT}/AmpUp.xcodeproj" -enableCodeCoverage YES -resultBundlePath "${TEST_RESULTS_PATH}"

TEST_EXIT_STATUS=${PIPESTATUS[0]}

if [ $TEST_EXIT_STATUS -ne 0 ]; then
    echo "Unit tests failed. Commit aborted."
else
    echo "Unit tests succeeded."
fi

echo "Code coverage summary:"
xcrun xccov view --report --only-targets "${TEST_RESULTS_PATH}"

exit 0